version: "3.1"
services:
    flask:
        build: .
        image: reclutamiento-flask:0.0.1
        command: waitress-serve --port="${APP_PORT}" --call "reclutamiento:create_app"
        env_file:
            - .env
        ports:
            - "${APP_PORT:-80}:80"
        networks:
            - network
        depends_on:
            postgres:
                condition: service_healthy
        restart: unless-stopped
    postgres:
        image: postgres:14.1-alpine
        ports:
            - "${DB_PORT:-5432}:5432"
        environment:
            POSTGRES_DB: "${DB_DATABASE}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - data:/var/lib/postgresql/data
            - ./scripts:/docker-entrypoint-initdb.d
        networks:
            - network
        healthcheck:
          test: ["CMD", "pg_isready"]
          retries: 5
          timeout: 5s
        restart: unless-stopped
    adminer:
        image: adminer:4.8.1
        ports:
            - "${DBADMIN_PORT:-8080}:8080"
        environment:
            ADMINER_DEFAULT_SERVER: "${DB_HOST}"
        networks:
            - network
        restart: unless-stopped
networks:
    network:
        driver: bridge
volumes:
    data:
        driver: local
