BEGIN TRANSACTION;

DROP TABLE IF EXISTS tbl_job;

CREATE TABLE tbl_job (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    author_id INT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title VARCHAR(100) NOT NULL,
    body TEXT NOT NULL
);

END TRANSACTION;